M48
; DRILL file {KiCad 9.0.7} date 2026-02-16T02:37:33+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-16T02:37:33+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X62.5Y-50.0
X67.5Y-50.0
T2
X47.46Y-50.0
X50.0Y-50.0
X52.54Y-50.0
M30
